import { relations } from "drizzle-orm";
import {
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { users } from "./auth";
import { pageRevisions, pages } from "./wiki";

// ---------------------------------------------------------------------------
// ai_providers
// ---------------------------------------------------------------------------

export const aiProviders = pgTable("ai_providers", {
  id: uuid("id").primaryKey().defaultRandom(),
  key: text("key").notNull().unique(),
  label: text("label").notNull(),
  // enum: openai | anthropic | ollama | custom
  providerType: text("provider_type").notNull(),
  // enum: disabled | enabled | error
  status: text("status").notNull().default("disabled"),
  capabilities: text("capabilities").array().notNull().default([]),
  endpoint: text("endpoint"),
  // AES-GCM encrypted JSON blob; key from ENCRYPTION_KEY env var
  encryptedCredentials: text("encrypted_credentials"),
  defaultModel: text("default_model"),
  embeddingModel: text("embedding_model"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ai_knowledge_records
// ---------------------------------------------------------------------------

export const aiKnowledgeRecords = pgTable("ai_knowledge_records", {
  id: uuid("id").primaryKey().defaultRandom(),
  pageRevisionId: uuid("page_revision_id")
    .notNull()
    .references(() => pageRevisions.id, { onDelete: "cascade" }),
  providerId: uuid("provider_id")
    .notNull()
    .references(() => aiProviders.id, { onDelete: "cascade" }),
  indexVersion: integer("index_version").notNull().default(1),
  summary: text("summary"),
  // Path or identifier for the stored vector (e.g. pgvector row id or object key)
  embeddingRef: text("embedding_ref"),
  entities: jsonb("entities"),
  citationAnchors: jsonb("citation_anchors"),
  // enum: pending | ready | failed
  ingestionStatus: text("ingestion_status").notNull().default("pending"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ai_conversations
// ---------------------------------------------------------------------------

export const aiConversations = pgTable("ai_conversations", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  providerId: uuid("provider_id").references(() => aiProviders.id, { onDelete: "set null" }),
  // enum: global | space | page
  contextType: text("context_type").notNull().default("global"),
  contextId: uuid("context_id"),
  title: text("title"),
  // enum: active | archived | deleted
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ai_conversation_messages
// ---------------------------------------------------------------------------

export const aiConversationMessages = pgTable("ai_conversation_messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id")
    .notNull()
    .references(() => aiConversations.id, { onDelete: "cascade" }),
  // enum: user | assistant | system
  role: text("role").notNull(),
  body: text("body").notNull(),
  // enum: pending | completed | failed
  status: text("status").notNull().default("completed"),
  // Tracks the page draft generated by an assistant message, if any
  generatedDraftPageId: uuid("generated_draft_page_id").references(() => pages.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// ai_citations
// ---------------------------------------------------------------------------

export const aiCitations = pgTable("ai_citations", {
  id: uuid("id").primaryKey().defaultRandom(),
  messageId: uuid("message_id")
    .notNull()
    .references(() => aiConversationMessages.id, { onDelete: "cascade" }),
  pageRevisionId: uuid("page_revision_id")
    .notNull()
    .references(() => pageRevisions.id, { onDelete: "cascade" }),
  excerptLocator: text("excerpt_locator"),
  orderIndex: integer("order_index").notNull().default(0),
});

// ---------------------------------------------------------------------------
// background_tasks
// ---------------------------------------------------------------------------

export const backgroundTasks = pgTable("background_tasks", {
  id: uuid("id").primaryKey().defaultRandom(),
  taskType: text("task_type").notNull(),
  requestedByUserId: uuid("requested_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  resourceType: text("resource_type"),
  resourceId: uuid("resource_id"),
  // enum: queued | running | completed | failed | cancelled
  status: text("status").notNull().default("queued"),
  progressLabel: text("progress_label"),
  errorSummary: text("error_summary"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
});

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

export const aiProvidersRelations = relations(aiProviders, ({ many }) => ({
  knowledgeRecords: many(aiKnowledgeRecords),
  conversations: many(aiConversations),
}));

export const aiKnowledgeRecordsRelations = relations(aiKnowledgeRecords, ({ one }) => ({
  pageRevision: one(pageRevisions, {
    fields: [aiKnowledgeRecords.pageRevisionId],
    references: [pageRevisions.id],
  }),
  provider: one(aiProviders, {
    fields: [aiKnowledgeRecords.providerId],
    references: [aiProviders.id],
  }),
}));

export const aiConversationsRelations = relations(aiConversations, ({ one, many }) => ({
  user: one(users, {
    fields: [aiConversations.userId],
    references: [users.id],
  }),
  provider: one(aiProviders, {
    fields: [aiConversations.providerId],
    references: [aiProviders.id],
  }),
  messages: many(aiConversationMessages),
}));

export const aiConversationMessagesRelations = relations(
  aiConversationMessages,
  ({ one, many }) => ({
    conversation: one(aiConversations, {
      fields: [aiConversationMessages.conversationId],
      references: [aiConversations.id],
    }),
    generatedDraftPage: one(pages, {
      fields: [aiConversationMessages.generatedDraftPageId],
      references: [pages.id],
    }),
    citations: many(aiCitations),
  }),
);

export const aiCitationsRelations = relations(aiCitations, ({ one }) => ({
  message: one(aiConversationMessages, {
    fields: [aiCitations.messageId],
    references: [aiConversationMessages.id],
  }),
  pageRevision: one(pageRevisions, {
    fields: [aiCitations.pageRevisionId],
    references: [pageRevisions.id],
  }),
}));

export const backgroundTasksRelations = relations(backgroundTasks, ({ one }) => ({
  requestedByUser: one(users, {
    fields: [backgroundTasks.requestedByUserId],
    references: [users.id],
  }),
}));
